version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SOCKET_API_KEY=${SOCKET_API_KEY}
      - REDIS_URL=redis://redis:6379
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  redis:
    image: redis:6.2.5
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: